# ===================================================
# This file controls benchmark parameters, formatting, tolerances, and other tunable settings for the project.
# All values here are read by main.py at runtime.
# ===================================================
# Languages to enable: Keys = language code used in code
# Values = subpackage names under `<pkg_root>.implementations`
# -------------------------
[languages]
python = "python"
cython = "cython"
c = "c"
cpp = "cpp"
rust = "rust"

[format]
# Number of significant figures to display for execution times in seconds
time_sigfigs = 5
# Number of decimal places to display for integral results
integral_decimals = 6
# Optional: if true, show commas in large integers (1,000,000)
show_thousands_sep = true

[sieve]
# Upper-bound test values for the Sieve of Eratosthenes benchmark.
# Each value is the maximum integer to test for primality.
# e.g. 100000 → find all primes <= 100,000
inputs = [10, 100000, 200000, 400000, 800000]
# Floating point tolerance for correctness checking vs. Python reference.
# Not usually critical for pure integer prime tests but is kept for consistency.
tolerance = 1e-9
# Optional: if true, also store and report the list of primes for small N
show_prime_list_for_small_n = true

[trapezoid]
# Integration start value 'a' and end value 'b'
a = 0.0
b = 1.0
# Numbers of sub-intervals to use for trapezoidal rule.
# Increasing n decreases step size h = (b - a)/n and improves accuracy.
inputs = [10, 1000000, 2000000, 4000000]
# Floating point tolerance for correctness checking
tolerance = 1e-8
